name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tcs:
    name: TCS

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: TCS check
        run: ./vendor/bin/ecs check --config tcs.php

  tlint:
    name: TLint

    continue-on-error: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: Tlint Lint
        run: vendor/bin/tlint
